### ISSUE TITLE
ALAAT Hours Tracking

### ISSUE THREAD

**Issue by LiavB2** [arnavk377/ALAAT#1]
**05/05/23:**
- [x] Liav: Plan out group project + Canva Model Here - 1 Hour

**05/08/23:**
- [x] Liav: Research and collaboration on implementing the likes feature on each photo and determining the best way to implement it - 1 hour
- [x] Arnav: Planning out Group Project and developing Canva diagram - 1 hour
- [x] Taiyo: Planning + Canva diagram - 0.25 hours
- [x] Adi: Research for theme to set up site - 0.5 hours

**05/09/23:**
- [x] Liav: Clean up repo to make it only our code - 0.5 hours
- [x] Arnav: Create Repositories for Site, begin styling and coding for our own needs - 1 hour
- [x] Amay: Plan out Group Project and develop Canva diagram - 1 hour

**05/10/23:**
- [x] Arnav: Researching how to use Machine Learning models - 0.75 hours
- [x] Taiyo: Planning ga - 0.25 hours
- [x] Adi: Research for theme to set up site - 0.25 hours

**05/11/23:**
- [x] Arnav: Researching Implementation of Machine Learning Models - 0.5 hours
- [x] Taiyo: Planning feature - 0.25 hours
- [x] Amay: Planning feature - 0.5 hours

**05/12/23:**
- [x] Arnav: Testing Machine Learning Model Code in Notebooks - 1 hour
- [x] Taiyo: Planning Feature - 0.25 hours
- [x] Adi: Research for theme to set up site - 0.25 hours

**05/13/23:**
- [x] Liav: Research frontend likes saving from last tri full-stack lessons and write the code in the backend - 1 hour
- [x] Arnav: Researching how to implement images API - 0.5 hours
- [x] Taiyo: Planning Front End - 0.25 hours
- [x] Amay: Research for theme to set up site - 0.25 hours

**05/14/23:**
- [x] Liav: Learning about Image uploading feature implementation - 0.5 hours
- [x] Arnav: Learning about Image uploading feature implementation - 0.5 hours
- [x] Taiyo: Planning Front End - 0.25 hours
- [x] Adi: Research for theme to set up site - 0.25 hours

**05/15/23:**
- [x] Taiyo: Making frontend of the site - 2 hours
- [x] Amay: Making frontend of the site - 2 hours

**05/16/23:**
- [x] Liav: Develop a few prototype like systems (with multiple designs) - 1.5 hours
- [x] Taiyo: Making frontend of the site - 1.5 hours
- [x] Adi: Making the database - 1 hour
- [x] Amay: Planning feature - 0.5 hours

**05/17/23:**
- [x] Taiyo: Photoswipe (photo carousel) - 1 hour
- [x] Adi: Making the database - 1 hour
- [x] Amay: Planning feature - 0.5 hours

**05/18/23:**
- [x] Liav: Photoswipe (photo carousel) - 1 hour
- [x] Taiyo: Photoswipe (photo carousel) - 1 hour
- [x] Adi: Making the database - 1 hour
- [x] Amay: Making frontend of the site - 1 hour

**05/19/23:**
- [x] Liav: Figure out how to attach a like button to every image on the gallery - 1 hour
- [x] Taiyo: Photoswipe JS backend - 1 hour
- [x] Adi: image drop frontend - 2 hours

**05/20/23:**
- [x] Liav: Research and Create a JavaScript loop in the gallery file that automatically puts a like button on every image file - 3 hours
- [x] Taiyo: Plan out and think of how to implement comments - 0.5 hours
- [x] Adi: Working on animation (on-going) - 1 hour
- [x] Amay: Making frontend of the site - 1 hour

**05/21/23:**
- [x] Liav: Make the team logo and figure out how to place it on the navbar and click it as a home button - 0.5 hours
- [x] Taiyo: Backend for comments - 2 hours
- [x] Adi: Making the database - 2 hours
- [x] Amay: Plan out and think of how to implement comments - 0.5 hours

**05/22/23:**
- [x] Liav: In class, finally figured out the comment board - 1 hour
- [x] Taiyo: Photoswipe JS backend - 1 hour
- [x] Adi: Sign up/in done - 1 hour
- [x] Amay: In class, helped Liav with the comment board - 1 hour

**05/23/23:**
- [x] Liav: Research with Taiyo on how to connect the backend for the comment board - 0.5 hours
- [x] Taiyo: Photoswipe JS backend - 1 hour
- [x] Adi: Helped Amay a bit for around 1 hour in class - 1 hour

**05/24/23:**
- [x] Liav: Figure out how to attach a like button to every image on the gallery - 1 hour
- [x] Taiyo: Photoswipe JS backend - 1 hour
- [x] Adi: image drop frontend - 2 hours
- [x] Amay: Fixing sign-up/in - 0.5 hours

**05/25/23:**
- [x] Liav: Research and Create a JavaScript loop in the gallery file that automatically puts a like button on every image file - 3.5 hours
- [x] Arnav: Adjusting Style of Site, Continue Work on Image Uploading - 1 hour
- [x] Taiyo: Plan out and think of how to implement comments - 0.5 hours
- [x] Adi: Working on animation (on-going) - 1 hour
- [x] Amay: Making the team logo and figure out how to place it on the navbar and click it as a home button - 0.5 hours

**05/26/23:**
- [x] Liav: Make the team logo and figure out how to place it on the navbar and click it as a home button - 0.5 hours
- [x] Arnav: Backend of Commenting Feature - 1.5 hours
- [x] Taiyo: Backend for comments - 2 hours
- [x] Adi: Making the database - 2 hours
- [x] Amay: In class, finally figured out the comment board - 1 hour

**05/27/23:**
- [x] Liav: Research with Taiyo on how to connect the backend for the comment board - 0.5 hours
- [x] Arnav: Backend of Commenting Feature - 1 hour
- [x] Taiyo: Photoswipe JS backend - 1 hour
- [x] Adi: Helped Amay a bit for around 1 hour in class - 1 hour
- [x] Amay: Research with Taiyo on how to connect the backend for the comment board - 0.5 hours

**05/28/23:**
- [x] Liav: Implement the final version of the like system with the individual picture file pages and the gallery file - 2 hours
- [x] Arnav: Adjusting Style of Site, Continue Work on Image Uploading - 1.5 hours
- [x] Taiyo: Photoswipe JS backend - 1 hour
- [x] Adi: image drop frontend - 2 hours
- [x] Amay: Research and Create a JavaScript loop in the gallery file that automatically puts a like button on every image file - 3.5 hours

**05/29/23:**
- [x] Liav: Implement the final version of the like system with the individual picture file pages and the gallery file - 2 hours
- [x] Arnav: Backend of Commenting Feature - 1 hour
- [x] Taiyo: Backend for comments - 2 hours
- [x] Adi: Making the database - 2 hours
- [x] Amay: Make the team logo and figure out how to place it on the navbar and click it as a home button - 0.5 hours

**05/30/23:**
- [x] Liav: Final touches on likes system - 2 hours
- [x] Arnav: Final touches on drag and drop uplead - 2 hours
- [x] Taiyo: Finish up bakcend for comments - 2 hours
- [x] Adi: Making sure everything works on deployed site and help with final touches on upload image feature- 2 hours
- [x] Amay: final touches on signup/login - 2 hours

**05/31/23:**
- [x] Everyone: Review on how we are going to present at Night at the Museum - 1 hour

---

Total hours worked:

- Liav: 16 hours
- Arnav: 22.5 hours
- Taiyo: 16.5 hours
- Adi: 24 hours
- Amay: 15 hours
